# -*- coding: utf-8 -*-
"""for_while_exercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7o2QDp0SdjgObTDHcbYgFBvJRKJgwBk

Precisamos imprimir um número para cada andar de um hotel de 20 andares. Porém, o dono do hotel é supersticioso e optou por não ter um 13° andar.

Escreva um código que imprima todos os números exceto o número 13.
Escreva mais dois códigos que resolvam o mesmo problema, mas dessa vez usando os outros dois tipos de laços de repetição aprendidos.

Como desafio, imprima eles em ordem decrescente (20, 19, 18...)
"""

for andar in range(1, 21):
    if andar != 13:
        print("Andar",andar)

andar = 20

while andar >= 1:
    if andar != 13:
        print("Andar",andar)
    andar -= 1

andar = 1

while andar <= 20:
    if andar == 13:
        andar += 1
        continue

    print("Andar",andar)
    andar += 1

    if andar > 20:
        break