# -*- coding: utf-8 -*-
"""Proz- aula4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ntYlbHBWSeGhsDOBVJofC4m50kblJX9Y
"""

bebida = "Suco de abacaxi"
preco = 10
alcoolica = False

comida = "Lasanha de abobrinhha"
preco_comida = 22.50

sobremesa = "Petit Gateau"
preco_sobremesa = 18
convidados = 5
orcamento = 50

total = (preco_comida * convidados) + (preco * 5) + (preco_sobremesa *3)
por_pessoa = total / convidados
troco = orcamento - por_pessoa

print("Tenho",orcamento)
print("O total é de",total)
print("Por pessoa é", por_pessoa)
print("O troco foi de", troco)

if (por_pessoa <= orcamento):
 print("Opa! Bora comer")
else: print("Vamos ter que lavar pratos!")

#print(comida)
#print(preco_comida)
#print(bebida, preco, alcoolica)
#print(type(bebida))
#print(type(preco))
#print(type(alcoolica))