# -*- coding: utf-8 -*-
"""exercicio3_indice_len_range.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17cr2E7_TedYH66ou9d9YFtNYxesvpA8z

Uma nova loja de cosméticos abriu no seu bairro e pediram para você elaborar um sistema que imprime na tela na frente da loja os novos produtos que chegaram.

O sistema da loja já tem um array com os produtos, você precisa apenas imprimir eles no terminal, um por um.

Como desafio opcional, tente imprimir cada produto com a frase "Temos [produto] à venda!" (ex. "Temos máscaras faciais à venda!").

lista_produtos = ['máscaras faciais', 'batons', 'esmaltes', 'perfumes', 'loções', 'xampus', 'sabonetes', 'delineadores']
"""

lista_produtos = ['máscaras faciais', 'batons', 'esmaltes', 'perfumes', 'loções', 'xampus', 'sabonetes', 'delineadores']

for i in range(len(lista_produtos)):
  print(lista_produtos[i])

lista_produtos = ['máscaras faciais', 'batons', 'esmaltes', 'perfumes', 'loções', 'xampus', 'sabonetes', 'delineadores']

for i in range(len(lista_produtos)):
  print("Aqui temos", lista_produtos[i],"à venda!")