# -*- coding: utf-8 -*-
"""arrays_exercio1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sQ11rDvZNyl82Q9RgNPPKi4rKStwfVRA

Declare dois arrays, cada um com um mínimo de cinco elementos, e imprima eles no terminal usando o comando print().
 - O primeiro array deve conter os produtos de uma loja da sua escolha (loja de comida, materiais de construção, música, etc).

- O segundo array deve conter os anos de nascimento de familiares e amigos seus.

Lembre-se de usar nomes descritivos para nomear cada variável, e de usar o tipo de dado apropriado para cada lista (strings, booleanos, números inteiros, floats).
"""

suco_fruta = ["Abacaxi com hortelã", "Goiaba", "Morango com leite", "Limonada Suíssa", "Laranja", "Pêssego"]
print(suco_fruta)

ano_nascimento = [1985, 2004, 2008, 2009, 2019, 1989]
print(ano_nascimento)