# -*- coding: utf-8 -*-
"""tratamento_de_erros_exercicio1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wft7ydpX8i-sV4u3QGKy5KxUNNnJCDIZ

Desenvolva um programa que recebe do usuário nome completo e ano de nascimento que seja entre 1922 e 2021.
A partir dessas informações, o sistema mostrará o nome do usuário e a idade que completou, ou completará, no ano atual (2022).

Caso o usuário não digite um número ou apareça um inválido no campo do ano, o sistema informará o erro e continuará perguntando até que um valor correto seja preenchido.
"""

def calcular_idade(ano_nascimento, ano_atual):
    idade = ano_atual - ano_nascimento
    return idade

def obter_ano_nascimento():
    while True:
        try:
            ano_nascimento = int(input("Digite o ano de nascimento (1922-2021): "))
            if 1922 <= ano_nascimento <= 2021:
                return ano_nascimento
            else:
                print("Ano fora do intervalo permitido. Tente novamente.")
        except ValueError:
            print("Erro: Digite um ano válido.")

if __name__ == "__main__":
    try:
        nome_completo = input("Digite seu nome completo: ")

        ano_atual = 2022
        ano_nascimento = obter_ano_nascimento()

        idade = calcular_idade(ano_nascimento, ano_atual)

        print(f"\nOlá, {nome_completo}!")
        print(f"Você completou ou completará {idade} anos no ano atual (2022).")
    except Exception as e:
        print(f"Erro inesperado: {e}")